import os

POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_DB = os.getenv("POSTGRES_DB", "fip_postgres")
POSTGRES_USER = os.getenv("POSTGRES_USER", "fip_postgres")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "fip_postgres")

KAFKA_SERVER = os.getenv("KAFKA_SERVER", "kafka:9092")

SHORT_SQUEEZE_THRESHOLD = 500000
LONG_SQUEEZE_THRESHOLD = 500000

ORDERFLOW_THRESHOLD = 0.6
ORDERBOOK_IMBALANCE_THRESHOLD = 0.2