import os

POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_DB = os.getenv("POSTGRES_DB", "fip_postgres")
POSTGRES_USER = os.getenv("POSTGRES_USER", "fip_postgres")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "fip_postgres")

KAFKA_SERVER = os.getenv("KAFKA_SERVER", "kafka:9092")

OPPORTUNITY_WINDOW = 20
REVERSAL_CONFIDENCE = 0.8
BREAKOUT_CONFIDENCE = 0.75
SQUEEZE_CONFIDENCE = 0.85

SCORE_STOP_HUNT = 3
SCORE_ABSORPTION = 2
SCORE_SWEEP = 2
SCORE_LIQUIDITY_VACUUM = 2
SCORE_SQUEEZE = 3
SCORE_ORDERFLOW_IMBALANCE = 2
SCORE_LIQUIDATION_SPIKE = 2

SCORE_LIQUIDITY_POOL = 3
SCORE_STOP_CLUSTER = 2
SCORE_THIN_LIQUIDITY = 2
SCORE_HIGH_LIQUIDITY = 1

LIQ_SPIKE = 5000

OPPORTUNITY_SCORE_THRESHOLD = 6