import os

POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_DB = os.getenv("POSTGRES_DB", "fip_postgres")
POSTGRES_USER = os.getenv("POSTGRES_USER", "fip_postgres")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "fip_postgres")

KAFKA_SERVER = os.getenv("KAFKA_SERVER", "kafka:9092")

STOP_CLUSTER_THRESHOLD = 15
LIQ_POOL_THRESHOLD = 100000
HIGH_LIQ_THRESHOLD = 500000
THIN_SPREAD_THRESHOLD = 5
THIN_DEPTH_THRESHOLD = 2